

SELECT      A.AUTHOR_ID, A.AUTHOR_NAME, B.CATEGORY, SUM(SALES*B.PRICE) AS TOTAL_SALES
FROM        AUTHOR      A
JOIN        BOOK        B
  ON        A.AUTHOR_ID = B.AUTHOR_ID
JOIN        BOOK_SALES  BS
  ON        B.BOOK_ID = BS.BOOK_ID
# SELECT      BS.BOOK_ID, BS.SALES
WHERE       SUBSTRING(BS.SALES_DATE, 1, 7) = "2022-01"
GROUP BY    A.AUTHOR_ID, B.CATEGORY
ORDER BY    A.AUTHOR_ID, B.CATEGORY DESC
;